# Generated by Django 3.0.2 on 2020-02-15 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('production', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=50)),
                ('year', models.IntegerField(max_length=4)),
                ('transmission', models.SmallIntegerField(choices=[(1, 'mechanik'), (2, 'machine'), (3, 'robot')])),
                ('color', models.CharField(max_length=20)),
            ],
        ),
    ]
